
from utilities.observers.Observable import Observable

class VehicleEventDispatcher(Observable):
    
    SOFTWARE_VERSION_EVENT = "Software Version"
    BOAR_TYPE_EVENT = "Board Type"
    FLIGHT_CONFIG_EVENT = "Flight Config"
    YAW_DIRECTION_CONFIG_EVENT = "Yaw Config"
    RECEIVER_TYPE_EVENT = "Receiver Type"
    RECEIVER_NB_CHANNEL_EVENT = "Receiver Channels"
    RECEIVER_CHANNELS_MAPS_EVENT = "Receiver Channels map"
    NUMBER_MOTORS_EVENT = "Motors"
    GYROSCOPE_DETECTED_EVENT = "Gyroscope"
    ACCELEROMETER_DETECTED_EVENT = "Accelerometer"
    BAROMETER_DETECTED_EVENT = "Barometer"
    MAGNETOMETER_DETECTED_EVENT = "Magnetometer"
    HEADING_HOLD_ENABLED_EVENT = "Heading Hold"
    ALTITUDE_HOLD_ENABLED_EVENT = "Altitude Hold"
    BATTERY_MONITOR_ENABLED_EVENT = "Battery Monitor"
    
    MOTOR_ARMED_PROPERTY_EVENT = "MOTOR_ARMED_PROPERTY_EVENT"
    VEHICLE_ROLL_PROPERTY_EVENT = "VEHICLE_ROLL_PROPERTY_EVENT"
    VEHICLE_PITCH_PROPERTY_EVENT = "VEHICLE_PITCH_PROPERTY_EVENT"
    VEHICLE_HEADING_PROPERTY_EVENT = "VEHICLE_HEADING_PROPERTY_EVENT"
    ALTITUDE_HOLD_STATE_PROPERTY_EVENT = "ALTITUDE_HOLD_STATE_PROPERTY_EVENT"
    VEHICLE_ALTITUDE_PROPERTY_EVENT = "VEHICLE_ALTITUDE_PROPERTY_EVENT"
    SONAR_DISTANCE_PROPERTY_EVENT = "SONAR_DISTANCE_PROPERTY_EVENT"
    
    RECEIVER_ROLL_PROPERTY_EVENT = "RECEIVER_ROLL_PROPERTY_EVENT" 
    RECEIVER_PITCH_PROPERTY_EVENT = "RECEIVER_PITCH_PROPERTY_EVENT"
    RECEIVER_YAW_PROPERTY_EVENT = "RECEIVER_YAW_PROPERTY_EVENT"
    RECEIVER_THROTTLE_PROPERTY_EVENT = "RECEIVER_THROTTLE_PROPERTY_EVENT"
    RECEIVER_MODE_PROPERTY_EVENT = "RECEIVER_MODE_PROPERTY_EVENT"
    RECEIVER_AUX1_PROPERTY_EVENT = "RECEIVER_AUX1_PROPERTY_EVENT"
    RECEIVER_AUX2_PROPERTY_EVENT = "RECEIVER_AUX2_PROPERTY_EVENT"
    RECEIVER_AUX3_PROPERTY_EVENT = "RECEIVER_AUX3_PROPERTY_EVENT"
    RECEIVER_AUX4_PROPERTY_EVENT = "RECEIVER_AUX4_PROPERTY_EVENT"
    RECEIVER_AUX5_PROPERTY_EVENT = "RECEIVER_AUX5_PROPERTY_EVENT"
    RECEIVER_AUX6_PROPERTY_EVENT = "RECEIVER_AUX6_PROPERTY_EVENT"
    RECEIVER_AUX7_PROPERTY_EVENT = "RECEIVER_AUX7_PROPERTY_EVENT"
    
    MOTOR1_THROTTLE_PROPERTY_EVENT = "MOTOR1_THROTTLE_PROPERTY_EVENT"
    MOTOR2_THROTTLE_PROPERTY_EVENT = "MOTOR2_THROTTLE_PROPERTY_EVENT"
    MOTOR3_THROTTLE_PROPERTY_EVENT = "MOTOR3_THROTTLE_PROPERTY_EVENT"
    MOTOR4_THROTTLE_PROPERTY_EVENT = "MOTOR4_THROTTLE_PROPERTY_EVENT"
    MOTOR5_THROTTLE_PROPERTY_EVENT = "MOTOR5_THROTTLE_PROPERTY_EVENT"
    MOTOR6_THROTTLE_PROPERTY_EVENT = "MOTOR6_THROTTLE_PROPERTY_EVENT"
    MOTOR7_THROTTLE_PROPERTY_EVENT = "MOTOR7_THROTTLE_PROPERTY_EVENT"
    MOTOR8_THROTTLE_PROPERTY_EVENT = "MOTOR8_THROTTLE_PROPERTY_EVENT"
    
    BATTERY_VOLTAGE_PROPERTY_EVENT = "BATTERY_VOLTAGE_PROPERTY_EVENT"
    
    FLIGHT_MODE_PROPERTY_EVENT = "FLIGHT_MODE_PROPERTY_EVENT"
    
    GYRO_DATA_EVENT = "GYRO_DATA_EVENT"
    ACCEL_DATA_EVENT = "ACCEL_DATA_EVENT"
    ACCEL_RAW_DATA_EVENT = "ACCEL_RAW_DATA_EVENT"
    MAGNETOMETER_DATA_EVENT = "MAGNETOMETER_DATA_EVENT"
    MAGNETOMETER_RAW_DATA_EVENT = "MAGNETOMETER_RAW_DATA_EVENT"
    
    PID_ACCRO_ROLL = "PID_ACCRO_ROLL"
    PID_ACCRO_PITCH = "PID_ACCRO_PITCH"
    PID_ACCRO_STICK_SCALING = "PID_ACCRO_STICK_SCALING"
    
    
    def __init__(self):
        Observable.__init__(self)
        
    def dispatch_event(self, property_name, value):
        self.dispatch(property_name, value)
        
        