# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RCcalibrationWindow.ui'
#
# Created: Thu Apr 04 23:15:12 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(800, 600)
        self.transmitterOutput = QtGui.QGraphicsView(Form)
        self.transmitterOutput.setGeometry(QtCore.QRect(107, 186, 300, 120))
        self.transmitterOutput.setMaximumSize(QtCore.QSize(16777215, 300))
        self.transmitterOutput.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:reflect, x1:0.548, y1:0.0170455, x2:0.548, y2:1, stop:0 rgba(30, 30, 30, 255), stop:1 rgba(66, 66, 66, 255))"))
        self.transmitterOutput.setFrameShape(QtGui.QFrame.Box)
        self.transmitterOutput.setFrameShadow(QtGui.QFrame.Plain)
        self.transmitterOutput.setLineWidth(2)
        self.transmitterOutput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.transmitterOutput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.transmitterOutput.setObjectName(_fromUtf8("transmitterOutput"))
        self.leftTransmitter = QtGui.QGraphicsView(Form)
        self.leftTransmitter.setGeometry(QtCore.QRect(107, 30, 147, 150))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftTransmitter.sizePolicy().hasHeightForWidth())
        self.leftTransmitter.setSizePolicy(sizePolicy)
        self.leftTransmitter.setMinimumSize(QtCore.QSize(147, 150))
        self.leftTransmitter.setMaximumSize(QtCore.QSize(147, 150))
        self.leftTransmitter.setFrameShape(QtGui.QFrame.Box)
        self.leftTransmitter.setFrameShadow(QtGui.QFrame.Plain)
        self.leftTransmitter.setLineWidth(2)
        self.leftTransmitter.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.leftTransmitter.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.leftTransmitter.setObjectName(_fromUtf8("leftTransmitter"))
        self.rightTransmitter = QtGui.QGraphicsView(Form)
        self.rightTransmitter.setGeometry(QtCore.QRect(260, 30, 147, 150))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightTransmitter.sizePolicy().hasHeightForWidth())
        self.rightTransmitter.setSizePolicy(sizePolicy)
        self.rightTransmitter.setMinimumSize(QtCore.QSize(147, 150))
        self.rightTransmitter.setMaximumSize(QtCore.QSize(147, 150))
        self.rightTransmitter.setFrameShape(QtGui.QFrame.Box)
        self.rightTransmitter.setFrameShadow(QtGui.QFrame.Plain)
        self.rightTransmitter.setLineWidth(2)
        self.rightTransmitter.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rightTransmitter.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rightTransmitter.setObjectName(_fromUtf8("rightTransmitter"))
        self.start = QtGui.QPushButton(Form)
        self.start.setGeometry(QtCore.QRect(450, 500, 100, 31))
        self.start.setObjectName(_fromUtf8("start"))
        self.cancel = QtGui.QPushButton(Form)
        self.cancel.setGeometry(QtCore.QRect(560, 500, 101, 31))
        self.cancel.setObjectName(_fromUtf8("cancel"))
        self.next = QtGui.QPushButton(Form)
        self.next.setGeometry(QtCore.QRect(670, 500, 101, 31))
        self.next.setObjectName(_fromUtf8("next"))
        self.progressBar_RCmode = QtGui.QProgressBar(Form)
        self.progressBar_RCmode.setGeometry(QtCore.QRect(110, 340, 200, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.progressBar_RCmode.setFont(font)
        self.progressBar_RCmode.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.progressBar_RCmode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_RCmode.setMinimum(1000)
        self.progressBar_RCmode.setMaximum(2000)
        self.progressBar_RCmode.setProperty("value", 1000)
        self.progressBar_RCmode.setTextVisible(True)
        self.progressBar_RCmode.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_RCmode.setInvertedAppearance(False)
        self.progressBar_RCmode.setObjectName(_fromUtf8("progressBar_RCmode"))
        self.progressBar_RCAux1 = QtGui.QProgressBar(Form)
        self.progressBar_RCAux1.setGeometry(QtCore.QRect(110, 370, 200, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.progressBar_RCAux1.setFont(font)
        self.progressBar_RCAux1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.progressBar_RCAux1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_RCAux1.setMinimum(1000)
        self.progressBar_RCAux1.setMaximum(2000)
        self.progressBar_RCAux1.setProperty("value", 1000)
        self.progressBar_RCAux1.setTextVisible(True)
        self.progressBar_RCAux1.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_RCAux1.setInvertedAppearance(False)
        self.progressBar_RCAux1.setObjectName(_fromUtf8("progressBar_RCAux1"))
        self.progressBar_RCAux2 = QtGui.QProgressBar(Form)
        self.progressBar_RCAux2.setGeometry(QtCore.QRect(110, 400, 200, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.progressBar_RCAux2.setFont(font)
        self.progressBar_RCAux2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.progressBar_RCAux2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_RCAux2.setMinimum(1000)
        self.progressBar_RCAux2.setMaximum(2000)
        self.progressBar_RCAux2.setProperty("value", 1000)
        self.progressBar_RCAux2.setTextVisible(True)
        self.progressBar_RCAux2.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_RCAux2.setInvertedAppearance(False)
        self.progressBar_RCAux2.setObjectName(_fromUtf8("progressBar_RCAux2"))
        self.progressBar_RCAux3 = QtGui.QProgressBar(Form)
        self.progressBar_RCAux3.setGeometry(QtCore.QRect(110, 430, 200, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.progressBar_RCAux3.setFont(font)
        self.progressBar_RCAux3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.progressBar_RCAux3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_RCAux3.setMinimum(1000)
        self.progressBar_RCAux3.setMaximum(2000)
        self.progressBar_RCAux3.setProperty("value", 1000)
        self.progressBar_RCAux3.setTextVisible(True)
        self.progressBar_RCAux3.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_RCAux3.setInvertedAppearance(False)
        self.progressBar_RCAux3.setObjectName(_fromUtf8("progressBar_RCAux3"))
        self.commLog = QtGui.QTextBrowser(Form)
        self.commLog.setGeometry(QtCore.QRect(430, 30, 341, 461))
        self.commLog.setFrameShadow(QtGui.QFrame.Sunken)
        self.commLog.setObjectName(_fromUtf8("commLog"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.start.setText(_translate("Form", "Start", None))
        self.cancel.setText(_translate("Form", "Cancel", None))
        self.next.setText(_translate("Form", "Next", None))
        self.progressBar_RCmode.setFormat(_translate("Form", "%v", None))
        self.progressBar_RCAux1.setFormat(_translate("Form", "%v", None))
        self.progressBar_RCAux2.setFormat(_translate("Form", "%v", None))
        self.progressBar_RCAux3.setFormat(_translate("Form", "%v", None))

