# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReceiverCalibrationPanel.ui'
#
# Created: Sun Jun 09 12:49:02 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReceiverCalibrationPanel(object):
    def setupUi(self, ReceiverCalibrationPanel):
        ReceiverCalibrationPanel.setObjectName(_fromUtf8("ReceiverCalibrationPanel"))
        ReceiverCalibrationPanel.resize(800, 600)
        self.left_transmitter = QtGui.QGraphicsView(ReceiverCalibrationPanel)
        self.left_transmitter.setGeometry(QtCore.QRect(77, 10, 147, 150))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_transmitter.sizePolicy().hasHeightForWidth())
        self.left_transmitter.setSizePolicy(sizePolicy)
        self.left_transmitter.setMinimumSize(QtCore.QSize(147, 150))
        self.left_transmitter.setMaximumSize(QtCore.QSize(147, 150))
        self.left_transmitter.setFrameShape(QtGui.QFrame.Box)
        self.left_transmitter.setFrameShadow(QtGui.QFrame.Plain)
        self.left_transmitter.setLineWidth(2)
        self.left_transmitter.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.left_transmitter.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.left_transmitter.setObjectName(_fromUtf8("left_transmitter"))
        self.right_transmitter = QtGui.QGraphicsView(ReceiverCalibrationPanel)
        self.right_transmitter.setGeometry(QtCore.QRect(230, 10, 147, 150))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_transmitter.sizePolicy().hasHeightForWidth())
        self.right_transmitter.setSizePolicy(sizePolicy)
        self.right_transmitter.setMinimumSize(QtCore.QSize(147, 150))
        self.right_transmitter.setMaximumSize(QtCore.QSize(147, 150))
        self.right_transmitter.setFrameShape(QtGui.QFrame.Box)
        self.right_transmitter.setFrameShadow(QtGui.QFrame.Plain)
        self.right_transmitter.setLineWidth(2)
        self.right_transmitter.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.right_transmitter.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.right_transmitter.setObjectName(_fromUtf8("right_transmitter"))
        self.start_button = QtGui.QPushButton(ReceiverCalibrationPanel)
        self.start_button.setGeometry(QtCore.QRect(450, 380, 100, 31))
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.cancel_button = QtGui.QPushButton(ReceiverCalibrationPanel)
        self.cancel_button.setGeometry(QtCore.QRect(570, 380, 101, 31))
        self.cancel_button.setObjectName(_fromUtf8("cancel_button"))
        self.mode_progress_bar = QtGui.QProgressBar(ReceiverCalibrationPanel)
        self.mode_progress_bar.setGeometry(QtCore.QRect(140, 176, 231, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.mode_progress_bar.setFont(font)
        self.mode_progress_bar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.mode_progress_bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mode_progress_bar.setMinimum(1000)
        self.mode_progress_bar.setMaximum(2000)
        self.mode_progress_bar.setProperty("value", 1000)
        self.mode_progress_bar.setTextVisible(True)
        self.mode_progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.mode_progress_bar.setInvertedAppearance(False)
        self.mode_progress_bar.setObjectName(_fromUtf8("mode_progress_bar"))
        self.aux1_progress_bar = QtGui.QProgressBar(ReceiverCalibrationPanel)
        self.aux1_progress_bar.setGeometry(QtCore.QRect(140, 206, 231, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.aux1_progress_bar.setFont(font)
        self.aux1_progress_bar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.aux1_progress_bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.aux1_progress_bar.setMinimum(1000)
        self.aux1_progress_bar.setMaximum(2000)
        self.aux1_progress_bar.setProperty("value", 1000)
        self.aux1_progress_bar.setTextVisible(True)
        self.aux1_progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.aux1_progress_bar.setInvertedAppearance(False)
        self.aux1_progress_bar.setObjectName(_fromUtf8("aux1_progress_bar"))
        self.aux2_progress_bar = QtGui.QProgressBar(ReceiverCalibrationPanel)
        self.aux2_progress_bar.setGeometry(QtCore.QRect(140, 236, 231, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.aux2_progress_bar.setFont(font)
        self.aux2_progress_bar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.aux2_progress_bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.aux2_progress_bar.setMinimum(1000)
        self.aux2_progress_bar.setMaximum(2000)
        self.aux2_progress_bar.setProperty("value", 1000)
        self.aux2_progress_bar.setTextVisible(True)
        self.aux2_progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.aux2_progress_bar.setInvertedAppearance(False)
        self.aux2_progress_bar.setObjectName(_fromUtf8("aux2_progress_bar"))
        self.aux3_progress_bar = QtGui.QProgressBar(ReceiverCalibrationPanel)
        self.aux3_progress_bar.setGeometry(QtCore.QRect(140, 266, 231, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.aux3_progress_bar.setFont(font)
        self.aux3_progress_bar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.aux3_progress_bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.aux3_progress_bar.setMinimum(1000)
        self.aux3_progress_bar.setMaximum(2000)
        self.aux3_progress_bar.setProperty("value", 1000)
        self.aux3_progress_bar.setTextVisible(True)
        self.aux3_progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.aux3_progress_bar.setInvertedAppearance(False)
        self.aux3_progress_bar.setObjectName(_fromUtf8("aux3_progress_bar"))
        self.comm_log = QtGui.QTextBrowser(ReceiverCalibrationPanel)
        self.comm_log.setGeometry(QtCore.QRect(450, 10, 341, 361))
        self.comm_log.setFrameShadow(QtGui.QFrame.Sunken)
        self.comm_log.setObjectName(_fromUtf8("comm_log"))
        self.aux4_progress_bar = QtGui.QProgressBar(ReceiverCalibrationPanel)
        self.aux4_progress_bar.setGeometry(QtCore.QRect(140, 296, 231, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.aux4_progress_bar.setFont(font)
        self.aux4_progress_bar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.aux4_progress_bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.aux4_progress_bar.setMinimum(1000)
        self.aux4_progress_bar.setMaximum(2000)
        self.aux4_progress_bar.setProperty("value", 1000)
        self.aux4_progress_bar.setTextVisible(True)
        self.aux4_progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.aux4_progress_bar.setInvertedAppearance(False)
        self.aux4_progress_bar.setObjectName(_fromUtf8("aux4_progress_bar"))
        self.aux5_progress_bar = QtGui.QProgressBar(ReceiverCalibrationPanel)
        self.aux5_progress_bar.setGeometry(QtCore.QRect(140, 326, 231, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.aux5_progress_bar.setFont(font)
        self.aux5_progress_bar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.aux5_progress_bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.aux5_progress_bar.setMinimum(1000)
        self.aux5_progress_bar.setMaximum(2000)
        self.aux5_progress_bar.setProperty("value", 1000)
        self.aux5_progress_bar.setTextVisible(True)
        self.aux5_progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.aux5_progress_bar.setInvertedAppearance(False)
        self.aux5_progress_bar.setObjectName(_fromUtf8("aux5_progress_bar"))
        self.aux7_progress_bar = QtGui.QProgressBar(ReceiverCalibrationPanel)
        self.aux7_progress_bar.setGeometry(QtCore.QRect(140, 386, 231, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.aux7_progress_bar.setFont(font)
        self.aux7_progress_bar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.aux7_progress_bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.aux7_progress_bar.setMinimum(1000)
        self.aux7_progress_bar.setMaximum(2000)
        self.aux7_progress_bar.setProperty("value", 1000)
        self.aux7_progress_bar.setTextVisible(True)
        self.aux7_progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.aux7_progress_bar.setInvertedAppearance(False)
        self.aux7_progress_bar.setObjectName(_fromUtf8("aux7_progress_bar"))
        self.aux6_progress_bar = QtGui.QProgressBar(ReceiverCalibrationPanel)
        self.aux6_progress_bar.setGeometry(QtCore.QRect(140, 356, 231, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.aux6_progress_bar.setFont(font)
        self.aux6_progress_bar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.aux6_progress_bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.aux6_progress_bar.setMinimum(1000)
        self.aux6_progress_bar.setMaximum(2000)
        self.aux6_progress_bar.setProperty("value", 1000)
        self.aux6_progress_bar.setTextVisible(True)
        self.aux6_progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.aux6_progress_bar.setInvertedAppearance(False)
        self.aux6_progress_bar.setObjectName(_fromUtf8("aux6_progress_bar"))
        self.label = QtGui.QLabel(ReceiverCalibrationPanel)
        self.label.setGeometry(QtCore.QRect(80, 181, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_aux1 = QtGui.QLabel(ReceiverCalibrationPanel)
        self.label_aux1.setGeometry(QtCore.QRect(80, 211, 46, 13))
        self.label_aux1.setObjectName(_fromUtf8("label_aux1"))
        self.label_aux2 = QtGui.QLabel(ReceiverCalibrationPanel)
        self.label_aux2.setGeometry(QtCore.QRect(80, 240, 46, 13))
        self.label_aux2.setObjectName(_fromUtf8("label_aux2"))
        self.label_aux3 = QtGui.QLabel(ReceiverCalibrationPanel)
        self.label_aux3.setGeometry(QtCore.QRect(80, 270, 46, 13))
        self.label_aux3.setObjectName(_fromUtf8("label_aux3"))
        self.label_aux4 = QtGui.QLabel(ReceiverCalibrationPanel)
        self.label_aux4.setGeometry(QtCore.QRect(80, 300, 46, 13))
        self.label_aux4.setObjectName(_fromUtf8("label_aux4"))
        self.label_aux5 = QtGui.QLabel(ReceiverCalibrationPanel)
        self.label_aux5.setGeometry(QtCore.QRect(80, 330, 46, 13))
        self.label_aux5.setObjectName(_fromUtf8("label_aux5"))
        self.label_aux6 = QtGui.QLabel(ReceiverCalibrationPanel)
        self.label_aux6.setGeometry(QtCore.QRect(80, 360, 46, 13))
        self.label_aux6.setObjectName(_fromUtf8("label_aux6"))
        self.label_aux7 = QtGui.QLabel(ReceiverCalibrationPanel)
        self.label_aux7.setGeometry(QtCore.QRect(80, 390, 46, 13))
        self.label_aux7.setObjectName(_fromUtf8("label_aux7"))

        self.retranslateUi(ReceiverCalibrationPanel)
        QtCore.QMetaObject.connectSlotsByName(ReceiverCalibrationPanel)

    def retranslateUi(self, ReceiverCalibrationPanel):
        ReceiverCalibrationPanel.setWindowTitle(_translate("ReceiverCalibrationPanel", "Form", None))
        self.start_button.setText(_translate("ReceiverCalibrationPanel", "Start", None))
        self.cancel_button.setText(_translate("ReceiverCalibrationPanel", "Cancel", None))
        self.mode_progress_bar.setFormat(_translate("ReceiverCalibrationPanel", "%v", None))
        self.aux1_progress_bar.setFormat(_translate("ReceiverCalibrationPanel", "%v", None))
        self.aux2_progress_bar.setFormat(_translate("ReceiverCalibrationPanel", "%v", None))
        self.aux3_progress_bar.setFormat(_translate("ReceiverCalibrationPanel", "%v", None))
        self.comm_log.setHtml(_translate("ReceiverCalibrationPanel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1) Press start to start the RC calibration.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2) Move all channels to the minimum and maximum value.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">3) When done press finish to save the calibration.</span></p></body></html>", None))
        self.aux4_progress_bar.setFormat(_translate("ReceiverCalibrationPanel", "%v", None))
        self.aux5_progress_bar.setFormat(_translate("ReceiverCalibrationPanel", "%v", None))
        self.aux7_progress_bar.setFormat(_translate("ReceiverCalibrationPanel", "%v", None))
        self.aux6_progress_bar.setFormat(_translate("ReceiverCalibrationPanel", "%v", None))
        self.label.setText(_translate("ReceiverCalibrationPanel", "Mode", None))
        self.label_aux1.setText(_translate("ReceiverCalibrationPanel", "Aux1", None))
        self.label_aux2.setText(_translate("ReceiverCalibrationPanel", "Aux2", None))
        self.label_aux3.setText(_translate("ReceiverCalibrationPanel", "Aux3", None))
        self.label_aux4.setText(_translate("ReceiverCalibrationPanel", "Aux4", None))
        self.label_aux5.setText(_translate("ReceiverCalibrationPanel", "Aux5", None))
        self.label_aux6.setText(_translate("ReceiverCalibrationPanel", "Aux6", None))
        self.label_aux7.setText(_translate("ReceiverCalibrationPanel", "Aux7", None))

