# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VehicleDynamicConfigPanel.ui'
#
# Created: Wed Apr 24 17:56:37 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_VehicleDynamicConfigPanel(object):
    def setupUi(self, VehicleDynamicConfigPanel):
        VehicleDynamicConfigPanel.setObjectName(_fromUtf8("VehicleDynamicConfigPanel"))
        VehicleDynamicConfigPanel.resize(614, 413)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        VehicleDynamicConfigPanel.setPalette(palette)
        self.gridLayout = QtGui.QGridLayout(VehicleDynamicConfigPanel)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 2, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 4, 1, 1)
        self.frame = QtGui.QFrame(VehicleDynamicConfigPanel)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.receiverTitle = QtGui.QLabel(self.frame)
        self.receiverTitle.setObjectName(_fromUtf8("receiverTitle"))
        self.gridLayout_4.addWidget(self.receiverTitle, 1, 0, 1, 1)
        self.motorTitle = QtGui.QLabel(self.frame)
        self.motorTitle.setObjectName(_fromUtf8("motorTitle"))
        self.gridLayout_4.addWidget(self.motorTitle, 3, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 7, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 6, 0, 1, 1)
        self.updateButton = QtGui.QPushButton(self.frame)
        self.updateButton.setObjectName(_fromUtf8("updateButton"))
        self.gridLayout_4.addWidget(self.updateButton, 6, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 0, 0, 1, 1)
        self.receiverFrame = QtGui.QFrame(self.frame)
        self.receiverFrame.setFrameShape(QtGui.QFrame.Box)
        self.receiverFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.receiverFrame.setObjectName(_fromUtf8("receiverFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.receiverFrame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ppmRecv = QtGui.QCheckBox(self.receiverFrame)
        self.ppmRecv.setObjectName(_fromUtf8("ppmRecv"))
        self.horizontalLayout.addWidget(self.ppmRecv)
        self.normalRecv = QtGui.QCheckBox(self.receiverFrame)
        self.normalRecv.setObjectName(_fromUtf8("normalRecv"))
        self.horizontalLayout.addWidget(self.normalRecv)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.channelCount = QtGui.QComboBox(self.receiverFrame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.channelCount.setPalette(palette)
        self.channelCount.setObjectName(_fromUtf8("channelCount"))
        self.channelCount.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.channelCount)
        self.channelCount_2 = QtGui.QLabel(self.receiverFrame)
        self.channelCount_2.setObjectName(_fromUtf8("channelCount_2"))
        self.horizontalLayout.addWidget(self.channelCount_2)
        self.gridLayout_4.addWidget(self.receiverFrame, 2, 0, 1, 2)
        self.motorConfigFrame = QtGui.QFrame(self.frame)
        self.motorConfigFrame.setFrameShape(QtGui.QFrame.Box)
        self.motorConfigFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.motorConfigFrame.setObjectName(_fromUtf8("motorConfigFrame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.motorConfigFrame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.triBox = QtGui.QCheckBox(self.motorConfigFrame)
        self.triBox.setObjectName(_fromUtf8("triBox"))
        self.gridLayout_2.addWidget(self.triBox, 0, 0, 1, 1)
        self.quadBox = QtGui.QCheckBox(self.motorConfigFrame)
        self.quadBox.setObjectName(_fromUtf8("quadBox"))
        self.gridLayout_2.addWidget(self.quadBox, 0, 1, 1, 1)
        self.y6Box = QtGui.QCheckBox(self.motorConfigFrame)
        self.y6Box.setObjectName(_fromUtf8("y6Box"))
        self.gridLayout_2.addWidget(self.y6Box, 0, 4, 1, 1)
        self.hexaPlusBox = QtGui.QCheckBox(self.motorConfigFrame)
        self.hexaPlusBox.setObjectName(_fromUtf8("hexaPlusBox"))
        self.gridLayout_2.addWidget(self.hexaPlusBox, 0, 7, 1, 1)
        self.hexaXBox = QtGui.QCheckBox(self.motorConfigFrame)
        self.hexaXBox.setObjectName(_fromUtf8("hexaXBox"))
        self.gridLayout_2.addWidget(self.hexaXBox, 0, 6, 1, 1)
        self.quadPlusBox = QtGui.QCheckBox(self.motorConfigFrame)
        self.quadPlusBox.setObjectName(_fromUtf8("quadPlusBox"))
        self.gridLayout_2.addWidget(self.quadPlusBox, 0, 2, 1, 1)
        self.quadY4Box = QtGui.QCheckBox(self.motorConfigFrame)
        self.quadY4Box.setObjectName(_fromUtf8("quadY4Box"))
        self.gridLayout_2.addWidget(self.quadY4Box, 0, 3, 1, 1)
        self.reverseRotation = QtGui.QCheckBox(self.motorConfigFrame)
        self.reverseRotation.setObjectName(_fromUtf8("reverseRotation"))
        self.gridLayout_2.addWidget(self.reverseRotation, 1, 0, 1, 3)
        self.gridLayout_4.addWidget(self.motorConfigFrame, 4, 0, 1, 2)
        self.gridLayout.addWidget(self.frame, 3, 3, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 3, 5, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 3, 6, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 0, 2, 1, 3)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 3, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 3, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 1, 2, 1, 3)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 5, 2, 1, 3)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 6, 2, 1, 3)

        self.retranslateUi(VehicleDynamicConfigPanel)
        QtCore.QMetaObject.connectSlotsByName(VehicleDynamicConfigPanel)

    def retranslateUi(self, VehicleDynamicConfigPanel):
        VehicleDynamicConfigPanel.setWindowTitle(_translate("VehicleDynamicConfigPanel", "Form", None))
        self.receiverTitle.setText(_translate("VehicleDynamicConfigPanel", "Receiver", None))
        self.motorTitle.setText(_translate("VehicleDynamicConfigPanel", "Motor Configuration", None))
        self.updateButton.setText(_translate("VehicleDynamicConfigPanel", "Update", None))
        self.ppmRecv.setText(_translate("VehicleDynamicConfigPanel", "PPM", None))
        self.normalRecv.setText(_translate("VehicleDynamicConfigPanel", "Normal", None))
        self.channelCount.setItemText(0, _translate("VehicleDynamicConfigPanel", "5", None))
        self.channelCount_2.setText(_translate("VehicleDynamicConfigPanel", "Channel Count", None))
        self.triBox.setText(_translate("VehicleDynamicConfigPanel", "Tri", None))
        self.quadBox.setText(_translate("VehicleDynamicConfigPanel", "Quad", None))
        self.y6Box.setText(_translate("VehicleDynamicConfigPanel", "Y6", None))
        self.hexaPlusBox.setText(_translate("VehicleDynamicConfigPanel", "Hexa +", None))
        self.hexaXBox.setText(_translate("VehicleDynamicConfigPanel", "Hexa X", None))
        self.quadPlusBox.setText(_translate("VehicleDynamicConfigPanel", "Quad +", None))
        self.quadY4Box.setText(_translate("VehicleDynamicConfigPanel", "Quad Y4", None))
        self.reverseRotation.setText(_translate("VehicleDynamicConfigPanel", "Reverse Motor Rotation", None))

