# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sat Apr 27 10:53:10 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(811, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/AQ/AeroQuadMacIcon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.status = QtGui.QLabel(self.centralwidget)
        self.status.setMinimumSize(QtCore.QSize(200, 0))
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName(_fromUtf8("status"))
        self.horizontalLayout.addWidget(self.status)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.comPort = QtGui.QComboBox(self.centralwidget)
        self.comPort.setMinimumSize(QtCore.QSize(0, 0))
        self.comPort.setEditable(True)
        self.comPort.setObjectName(_fromUtf8("comPort"))
        self.horizontalLayout.addWidget(self.comPort)
        self.baudRate = QtGui.QComboBox(self.centralwidget)
        self.baudRate.setMinimumSize(QtCore.QSize(0, 0))
        self.baudRate.setEditable(True)
        self.baudRate.setObjectName(_fromUtf8("baudRate"))
        self.horizontalLayout.addWidget(self.baudRate)
        self.buttonConnect = QtGui.QPushButton(self.centralwidget)
        self.buttonConnect.setObjectName(_fromUtf8("buttonConnect"))
        self.horizontalLayout.addWidget(self.buttonConnect)
        self.buttonDisconnect = QtGui.QPushButton(self.centralwidget)
        self.buttonDisconnect.setObjectName(_fromUtf8("buttonDisconnect"))
        self.horizontalLayout.addWidget(self.buttonDisconnect)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.subPanel = QtGui.QStackedWidget(self.centralwidget)
        self.subPanel.setObjectName(_fromUtf8("subPanel"))
        self.gridLayout.addWidget(self.subPanel, 0, 1, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 1, 1, 1)
        self.SideMenu = QtGui.QToolBox(self.centralwidget)
        self.SideMenu.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SideMenu.setFont(font)
        self.SideMenu.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SideMenu.setFrameShadow(QtGui.QFrame.Plain)
        self.SideMenu.setObjectName(_fromUtf8("SideMenu"))
        self.SideMenuPage1 = QtGui.QWidget()
        self.SideMenuPage1.setGeometry(QtCore.QRect(0, 0, 179, 229))
        self.SideMenuPage1.setObjectName(_fromUtf8("SideMenuPage1"))
        self.sidemenu_button_vehicle_status = QtGui.QPushButton(self.SideMenuPage1)
        self.sidemenu_button_vehicle_status.setGeometry(QtCore.QRect(3, 0, 176, 23))
        self.sidemenu_button_vehicle_status.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_vehicle_status.setFont(font)
        self.sidemenu_button_vehicle_status.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_vehicle_status.setAutoFillBackground(False)
        self.sidemenu_button_vehicle_status.setStyleSheet(_fromUtf8("text-align: left"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/arrow_right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sidemenu_button_vehicle_status.setIcon(icon1)
        self.sidemenu_button_vehicle_status.setDefault(False)
        self.sidemenu_button_vehicle_status.setFlat(True)
        self.sidemenu_button_vehicle_status.setObjectName(_fromUtf8("sidemenu_button_vehicle_status"))
        self.sidemenu_button_vehicle_configuration = QtGui.QPushButton(self.SideMenuPage1)
        self.sidemenu_button_vehicle_configuration.setGeometry(QtCore.QRect(3, 20, 176, 23))
        self.sidemenu_button_vehicle_configuration.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_vehicle_configuration.setFont(font)
        self.sidemenu_button_vehicle_configuration.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_vehicle_configuration.setAutoFillBackground(False)
        self.sidemenu_button_vehicle_configuration.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_vehicle_configuration.setIcon(icon1)
        self.sidemenu_button_vehicle_configuration.setDefault(False)
        self.sidemenu_button_vehicle_configuration.setFlat(True)
        self.sidemenu_button_vehicle_configuration.setObjectName(_fromUtf8("sidemenu_button_vehicle_configuration"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SideMenu.addItem(self.SideMenuPage1, icon2, _fromUtf8(""))
        self.SideMenuPage2 = QtGui.QWidget()
        self.SideMenuPage2.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.SideMenuPage2.setObjectName(_fromUtf8("SideMenuPage2"))
        self.sidemenu_button_vehicle_setup = QtGui.QPushButton(self.SideMenuPage2)
        self.sidemenu_button_vehicle_setup.setGeometry(QtCore.QRect(3, 0, 176, 23))
        self.sidemenu_button_vehicle_setup.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_vehicle_setup.setFont(font)
        self.sidemenu_button_vehicle_setup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_vehicle_setup.setAutoFillBackground(False)
        self.sidemenu_button_vehicle_setup.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_vehicle_setup.setIcon(icon1)
        self.sidemenu_button_vehicle_setup.setDefault(False)
        self.sidemenu_button_vehicle_setup.setFlat(True)
        self.sidemenu_button_vehicle_setup.setObjectName(_fromUtf8("sidemenu_button_vehicle_setup"))
        self.sidemenu_button_sensors_calibration = QtGui.QPushButton(self.SideMenuPage2)
        self.sidemenu_button_sensors_calibration.setGeometry(QtCore.QRect(3, 20, 176, 23))
        self.sidemenu_button_sensors_calibration.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_sensors_calibration.setFont(font)
        self.sidemenu_button_sensors_calibration.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_sensors_calibration.setAutoFillBackground(False)
        self.sidemenu_button_sensors_calibration.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_sensors_calibration.setIcon(icon1)
        self.sidemenu_button_sensors_calibration.setDefault(False)
        self.sidemenu_button_sensors_calibration.setFlat(True)
        self.sidemenu_button_sensors_calibration.setObjectName(_fromUtf8("sidemenu_button_sensors_calibration"))
        self.sidemenu_button_magnetometer_calibration = QtGui.QPushButton(self.SideMenuPage2)
        self.sidemenu_button_magnetometer_calibration.setGeometry(QtCore.QRect(3, 40, 176, 23))
        self.sidemenu_button_magnetometer_calibration.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_magnetometer_calibration.setFont(font)
        self.sidemenu_button_magnetometer_calibration.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_magnetometer_calibration.setAutoFillBackground(False)
        self.sidemenu_button_magnetometer_calibration.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_magnetometer_calibration.setIcon(icon1)
        self.sidemenu_button_magnetometer_calibration.setDefault(False)
        self.sidemenu_button_magnetometer_calibration.setFlat(True)
        self.sidemenu_button_magnetometer_calibration.setObjectName(_fromUtf8("sidemenu_button_magnetometer_calibration"))
        self.sidemenu_button_RC_channels_detection = QtGui.QPushButton(self.SideMenuPage2)
        self.sidemenu_button_RC_channels_detection.setGeometry(QtCore.QRect(3, 60, 176, 23))
        self.sidemenu_button_RC_channels_detection.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_RC_channels_detection.setFont(font)
        self.sidemenu_button_RC_channels_detection.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_RC_channels_detection.setAutoFillBackground(False)
        self.sidemenu_button_RC_channels_detection.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_RC_channels_detection.setIcon(icon1)
        self.sidemenu_button_RC_channels_detection.setDefault(False)
        self.sidemenu_button_RC_channels_detection.setFlat(True)
        self.sidemenu_button_RC_channels_detection.setObjectName(_fromUtf8("sidemenu_button_RC_channels_detection"))
        self.sidemenu_button_RC_calibartion = QtGui.QPushButton(self.SideMenuPage2)
        self.sidemenu_button_RC_calibartion.setGeometry(QtCore.QRect(3, 80, 176, 23))
        self.sidemenu_button_RC_calibartion.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_RC_calibartion.setFont(font)
        self.sidemenu_button_RC_calibartion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_RC_calibartion.setAutoFillBackground(False)
        self.sidemenu_button_RC_calibartion.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_RC_calibartion.setIcon(icon1)
        self.sidemenu_button_RC_calibartion.setDefault(False)
        self.sidemenu_button_RC_calibartion.setFlat(True)
        self.sidemenu_button_RC_calibartion.setObjectName(_fromUtf8("sidemenu_button_RC_calibartion"))
        self.sidemenu_button_motor_command = QtGui.QPushButton(self.SideMenuPage2)
        self.sidemenu_button_motor_command.setGeometry(QtCore.QRect(3, 100, 176, 23))
        self.sidemenu_button_motor_command.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_motor_command.setFont(font)
        self.sidemenu_button_motor_command.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_motor_command.setAutoFillBackground(False)
        self.sidemenu_button_motor_command.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_motor_command.setIcon(icon1)
        self.sidemenu_button_motor_command.setDefault(False)
        self.sidemenu_button_motor_command.setFlat(True)
        self.sidemenu_button_motor_command.setObjectName(_fromUtf8("sidemenu_button_motor_command"))
        self.sidemenu_button_PID_update = QtGui.QPushButton(self.SideMenuPage2)
        self.sidemenu_button_PID_update.setGeometry(QtCore.QRect(3, 120, 176, 23))
        self.sidemenu_button_PID_update.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_PID_update.setFont(font)
        self.sidemenu_button_PID_update.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_PID_update.setAutoFillBackground(False)
        self.sidemenu_button_PID_update.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_PID_update.setIcon(icon1)
        self.sidemenu_button_PID_update.setDefault(False)
        self.sidemenu_button_PID_update.setFlat(True)
        self.sidemenu_button_PID_update.setObjectName(_fromUtf8("sidemenu_button_PID_update"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SideMenu.addItem(self.SideMenuPage2, icon3, _fromUtf8(""))
        self.SideMenuPage3 = QtGui.QWidget()
        self.SideMenuPage3.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.SideMenuPage3.setObjectName(_fromUtf8("SideMenuPage3"))
        self.sidemenu_button_serial_monitor = QtGui.QPushButton(self.SideMenuPage3)
        self.sidemenu_button_serial_monitor.setGeometry(QtCore.QRect(3, 0, 176, 23))
        self.sidemenu_button_serial_monitor.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_serial_monitor.setFont(font)
        self.sidemenu_button_serial_monitor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_serial_monitor.setAutoFillBackground(False)
        self.sidemenu_button_serial_monitor.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_serial_monitor.setIcon(icon1)
        self.sidemenu_button_serial_monitor.setDefault(False)
        self.sidemenu_button_serial_monitor.setFlat(True)
        self.sidemenu_button_serial_monitor.setObjectName(_fromUtf8("sidemenu_button_serial_monitor"))
        self.sidemenu_button_sensor_data = QtGui.QPushButton(self.SideMenuPage3)
        self.sidemenu_button_sensor_data.setGeometry(QtCore.QRect(3, 20, 176, 23))
        self.sidemenu_button_sensor_data.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_sensor_data.setFont(font)
        self.sidemenu_button_sensor_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_sensor_data.setAutoFillBackground(False)
        self.sidemenu_button_sensor_data.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_sensor_data.setIcon(icon1)
        self.sidemenu_button_sensor_data.setDefault(False)
        self.sidemenu_button_sensor_data.setFlat(True)
        self.sidemenu_button_sensor_data.setObjectName(_fromUtf8("sidemenu_button_sensor_data"))
        self.sidemenu_button_gyroscope_data = QtGui.QPushButton(self.SideMenuPage3)
        self.sidemenu_button_gyroscope_data.setGeometry(QtCore.QRect(3, 40, 176, 23))
        self.sidemenu_button_gyroscope_data.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_gyroscope_data.setFont(font)
        self.sidemenu_button_gyroscope_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_gyroscope_data.setAutoFillBackground(False)
        self.sidemenu_button_gyroscope_data.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_gyroscope_data.setIcon(icon1)
        self.sidemenu_button_gyroscope_data.setDefault(False)
        self.sidemenu_button_gyroscope_data.setFlat(True)
        self.sidemenu_button_gyroscope_data.setObjectName(_fromUtf8("sidemenu_button_gyroscope_data"))
        self.sidemenu_button_accelerometer_data = QtGui.QPushButton(self.SideMenuPage3)
        self.sidemenu_button_accelerometer_data.setGeometry(QtCore.QRect(3, 60, 176, 23))
        self.sidemenu_button_accelerometer_data.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_accelerometer_data.setFont(font)
        self.sidemenu_button_accelerometer_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_accelerometer_data.setAutoFillBackground(False)
        self.sidemenu_button_accelerometer_data.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_accelerometer_data.setIcon(icon1)
        self.sidemenu_button_accelerometer_data.setDefault(False)
        self.sidemenu_button_accelerometer_data.setFlat(True)
        self.sidemenu_button_accelerometer_data.setObjectName(_fromUtf8("sidemenu_button_accelerometer_data"))
        self.sidemenu_button_magnetometer_data = QtGui.QPushButton(self.SideMenuPage3)
        self.sidemenu_button_magnetometer_data.setGeometry(QtCore.QRect(3, 80, 176, 23))
        self.sidemenu_button_magnetometer_data.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_magnetometer_data.setFont(font)
        self.sidemenu_button_magnetometer_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_magnetometer_data.setAutoFillBackground(False)
        self.sidemenu_button_magnetometer_data.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_magnetometer_data.setIcon(icon1)
        self.sidemenu_button_magnetometer_data.setDefault(False)
        self.sidemenu_button_magnetometer_data.setFlat(True)
        self.sidemenu_button_magnetometer_data.setObjectName(_fromUtf8("sidemenu_button_magnetometer_data"))
        self.sidemenu_button_attitude_data = QtGui.QPushButton(self.SideMenuPage3)
        self.sidemenu_button_attitude_data.setGeometry(QtCore.QRect(3, 100, 176, 23))
        self.sidemenu_button_attitude_data.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_attitude_data.setFont(font)
        self.sidemenu_button_attitude_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_attitude_data.setAutoFillBackground(False)
        self.sidemenu_button_attitude_data.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_attitude_data.setIcon(icon1)
        self.sidemenu_button_attitude_data.setDefault(False)
        self.sidemenu_button_attitude_data.setFlat(True)
        self.sidemenu_button_attitude_data.setObjectName(_fromUtf8("sidemenu_button_attitude_data"))
        self.sidemenu_button_transmitter_data = QtGui.QPushButton(self.SideMenuPage3)
        self.sidemenu_button_transmitter_data.setGeometry(QtCore.QRect(3, 120, 176, 23))
        self.sidemenu_button_transmitter_data.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_transmitter_data.setFont(font)
        self.sidemenu_button_transmitter_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_transmitter_data.setAutoFillBackground(False)
        self.sidemenu_button_transmitter_data.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_transmitter_data.setIcon(icon1)
        self.sidemenu_button_transmitter_data.setDefault(False)
        self.sidemenu_button_transmitter_data.setFlat(True)
        self.sidemenu_button_transmitter_data.setObjectName(_fromUtf8("sidemenu_button_transmitter_data"))
        self.sidemenu_button_altitude_data = QtGui.QPushButton(self.SideMenuPage3)
        self.sidemenu_button_altitude_data.setGeometry(QtCore.QRect(3, 140, 176, 23))
        self.sidemenu_button_altitude_data.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.sidemenu_button_altitude_data.setFont(font)
        self.sidemenu_button_altitude_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidemenu_button_altitude_data.setAutoFillBackground(False)
        self.sidemenu_button_altitude_data.setStyleSheet(_fromUtf8("text-align: left"))
        self.sidemenu_button_altitude_data.setIcon(icon1)
        self.sidemenu_button_altitude_data.setDefault(False)
        self.sidemenu_button_altitude_data.setFlat(True)
        self.sidemenu_button_altitude_data.setObjectName(_fromUtf8("sidemenu_button_altitude_data"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/graphic.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SideMenu.addItem(self.SideMenuPage3, icon4, _fromUtf8(""))
        self.gridLayout.addWidget(self.SideMenu, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtGui.QMenu(self.menuFile)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuCalibrations = QtGui.QMenu(self.menuFile)
        self.menuCalibrations.setObjectName(_fromUtf8("menuCalibrations"))
        self.menuPreferences = QtGui.QMenu(self.menuFile)
        self.menuPreferences.setObjectName(_fromUtf8("menuPreferences"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOpenSettings = QtGui.QAction(MainWindow)
        self.actionOpenSettings.setObjectName(_fromUtf8("actionOpenSettings"))
        self.actionSaveSettings = QtGui.QAction(MainWindow)
        self.actionSaveSettings.setObjectName(_fromUtf8("actionSaveSettings"))
        self.actionOpenCalibrations = QtGui.QAction(MainWindow)
        self.actionOpenCalibrations.setObjectName(_fromUtf8("actionOpenCalibrations"))
        self.actionSaveCalibrations = QtGui.QAction(MainWindow)
        self.actionSaveCalibrations.setObjectName(_fromUtf8("actionSaveCalibrations"))
        self.actionBootUpDelay = QtGui.QAction(MainWindow)
        self.actionBootUpDelay.setObjectName(_fromUtf8("actionBootUpDelay"))
        self.actionCommTimeout = QtGui.QAction(MainWindow)
        self.actionCommTimeout.setObjectName(_fromUtf8("actionCommTimeout"))
        self.menuSettings.addAction(self.actionOpenSettings)
        self.menuSettings.addAction(self.actionSaveSettings)
        self.menuCalibrations.addAction(self.actionOpenCalibrations)
        self.menuCalibrations.addAction(self.actionSaveCalibrations)
        self.menuPreferences.addAction(self.actionBootUpDelay)
        self.menuPreferences.addAction(self.actionCommTimeout)
        self.menuFile.addAction(self.menuSettings.menuAction())
        self.menuFile.addAction(self.menuCalibrations.menuAction())
        self.menuFile.addAction(self.menuPreferences.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.SideMenu.setCurrentIndex(0)
        self.SideMenu.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "AeroQuad Configurator", None))
        self.status.setText(_translate("MainWindow", "Not connected to AeroQuad", None))
        self.buttonConnect.setText(_translate("MainWindow", "Connect", None))
        self.buttonDisconnect.setText(_translate("MainWindow", "Disconnect", None))
        self.sidemenu_button_vehicle_status.setText(_translate("MainWindow", "Vehicle status", None))
        self.sidemenu_button_vehicle_configuration.setText(_translate("MainWindow", "Vehicle configuration", None))
        self.SideMenu.setItemText(self.SideMenu.indexOf(self.SideMenuPage1), _translate("MainWindow", "Info", None))
        self.sidemenu_button_vehicle_setup.setText(_translate("MainWindow", "Vehicle setup", None))
        self.sidemenu_button_sensors_calibration.setText(_translate("MainWindow", "Sensors calibration", None))
        self.sidemenu_button_magnetometer_calibration.setText(_translate("MainWindow", "Magnetometer calibration", None))
        self.sidemenu_button_RC_channels_detection.setText(_translate("MainWindow", "RC channels detection", None))
        self.sidemenu_button_RC_calibartion.setText(_translate("MainWindow", "RC calibration", None))
        self.sidemenu_button_motor_command.setText(_translate("MainWindow", "Motor command", None))
        self.sidemenu_button_PID_update.setText(_translate("MainWindow", "PID update", None))
        self.SideMenu.setItemText(self.SideMenu.indexOf(self.SideMenuPage2), _translate("MainWindow", "Settings", None))
        self.sidemenu_button_serial_monitor.setText(_translate("MainWindow", "Serial monitor", None))
        self.sidemenu_button_sensor_data.setText(_translate("MainWindow", "Sensor data", None))
        self.sidemenu_button_gyroscope_data.setText(_translate("MainWindow", "Gyroscope data", None))
        self.sidemenu_button_accelerometer_data.setText(_translate("MainWindow", "Accelerometer data", None))
        self.sidemenu_button_magnetometer_data.setText(_translate("MainWindow", "Magnetometer data", None))
        self.sidemenu_button_attitude_data.setText(_translate("MainWindow", "Attitude data", None))
        self.sidemenu_button_transmitter_data.setText(_translate("MainWindow", "Transmitter data", None))
        self.sidemenu_button_altitude_data.setText(_translate("MainWindow", "Altitude data", None))
        self.SideMenu.setItemText(self.SideMenu.indexOf(self.SideMenuPage3), _translate("MainWindow", "Data plot", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuCalibrations.setTitle(_translate("MainWindow", "Calibrations", None))
        self.menuPreferences.setTitle(_translate("MainWindow", "Preferences", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionOpenSettings.setText(_translate("MainWindow", "Open...", None))
        self.actionSaveSettings.setText(_translate("MainWindow", "Save...", None))
        self.actionOpenCalibrations.setText(_translate("MainWindow", "Open...", None))
        self.actionSaveCalibrations.setText(_translate("MainWindow", "Save....", None))
        self.actionBootUpDelay.setText(_translate("MainWindow", "Boot Up Delay...", None))
        self.actionCommTimeout.setText(_translate("MainWindow", "Comm Timeout...", None))

import AQresources_rc
