# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Fri Apr 26 17:05:27 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/AQ/AeroQuadMacIcon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.buttonMenu = QtGui.QPushButton(self.centralwidget)
        self.buttonMenu.setObjectName(_fromUtf8("buttonMenu"))
        self.horizontalLayout.addWidget(self.buttonMenu)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.status = QtGui.QLabel(self.centralwidget)
        self.status.setMinimumSize(QtCore.QSize(200, 0))
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName(_fromUtf8("status"))
        self.horizontalLayout.addWidget(self.status)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.comPort = QtGui.QComboBox(self.centralwidget)
        self.comPort.setMinimumSize(QtCore.QSize(0, 0))
        self.comPort.setEditable(True)
        self.comPort.setObjectName(_fromUtf8("comPort"))
        self.horizontalLayout.addWidget(self.comPort)
        self.baudRate = QtGui.QComboBox(self.centralwidget)
        self.baudRate.setMinimumSize(QtCore.QSize(0, 0))
        self.baudRate.setEditable(True)
        self.baudRate.setObjectName(_fromUtf8("baudRate"))
        self.horizontalLayout.addWidget(self.baudRate)
        self.buttonConnect = QtGui.QPushButton(self.centralwidget)
        self.buttonConnect.setObjectName(_fromUtf8("buttonConnect"))
        self.horizontalLayout.addWidget(self.buttonConnect)
        self.buttonDisconnect = QtGui.QPushButton(self.centralwidget)
        self.buttonDisconnect.setObjectName(_fromUtf8("buttonDisconnect"))
        self.horizontalLayout.addWidget(self.buttonDisconnect)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.subPanel = QtGui.QStackedWidget(self.centralwidget)
        self.subPanel.setObjectName(_fromUtf8("subPanel"))
        self.gridLayout.addWidget(self.subPanel, 0, 1, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 1, 1, 1)
        self.SideMenu = QtGui.QToolBox(self.centralwidget)
        self.SideMenu.setObjectName(_fromUtf8("SideMenu"))
        self.SideMenuPage1 = QtGui.QWidget()
        self.SideMenuPage1.setObjectName(_fromUtf8("SideMenuPage1"))
        self.pushButton = QtGui.QPushButton(self.SideMenuPage1)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 81, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.SideMenu.addItem(self.SideMenuPage1, icon1, _fromUtf8(""))
        self.SideMenuPage2 = QtGui.QWidget()
        self.SideMenuPage2.setObjectName(_fromUtf8("SideMenuPage2"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SideMenu.addItem(self.SideMenuPage2, icon2, _fromUtf8(""))
        self.SideMenuPage3 = QtGui.QWidget()
        self.SideMenuPage3.setObjectName(_fromUtf8("SideMenuPage3"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./resources/graphic.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SideMenu.addItem(self.SideMenuPage3, icon3, _fromUtf8(""))
        self.gridLayout.addWidget(self.SideMenu, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtGui.QMenu(self.menuFile)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuCalibrations = QtGui.QMenu(self.menuFile)
        self.menuCalibrations.setObjectName(_fromUtf8("menuCalibrations"))
        self.menuPreferences = QtGui.QMenu(self.menuFile)
        self.menuPreferences.setObjectName(_fromUtf8("menuPreferences"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOpenSettings = QtGui.QAction(MainWindow)
        self.actionOpenSettings.setObjectName(_fromUtf8("actionOpenSettings"))
        self.actionSaveSettings = QtGui.QAction(MainWindow)
        self.actionSaveSettings.setObjectName(_fromUtf8("actionSaveSettings"))
        self.actionOpenCalibrations = QtGui.QAction(MainWindow)
        self.actionOpenCalibrations.setObjectName(_fromUtf8("actionOpenCalibrations"))
        self.actionSaveCalibrations = QtGui.QAction(MainWindow)
        self.actionSaveCalibrations.setObjectName(_fromUtf8("actionSaveCalibrations"))
        self.actionBootUpDelay = QtGui.QAction(MainWindow)
        self.actionBootUpDelay.setObjectName(_fromUtf8("actionBootUpDelay"))
        self.actionCommTimeout = QtGui.QAction(MainWindow)
        self.actionCommTimeout.setObjectName(_fromUtf8("actionCommTimeout"))
        self.menuSettings.addAction(self.actionOpenSettings)
        self.menuSettings.addAction(self.actionSaveSettings)
        self.menuCalibrations.addAction(self.actionOpenCalibrations)
        self.menuCalibrations.addAction(self.actionSaveCalibrations)
        self.menuPreferences.addAction(self.actionBootUpDelay)
        self.menuPreferences.addAction(self.actionCommTimeout)
        self.menuFile.addAction(self.menuSettings.menuAction())
        self.menuFile.addAction(self.menuCalibrations.menuAction())
        self.menuFile.addAction(self.menuPreferences.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.SideMenu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "AeroQuad Configurator", None))
        self.buttonMenu.setText(_translate("MainWindow", "Menu", None))
        self.status.setText(_translate("MainWindow", "Not connected to AeroQuad", None))
        self.buttonConnect.setText(_translate("MainWindow", "Connect", None))
        self.buttonDisconnect.setText(_translate("MainWindow", "Disconnect", None))
        self.pushButton.setText(_translate("MainWindow", "PushButton", None))
        self.SideMenu.setItemText(self.SideMenu.indexOf(self.SideMenuPage1), _translate("MainWindow", "Info", None))
        self.SideMenu.setItemText(self.SideMenu.indexOf(self.SideMenuPage2), _translate("MainWindow", "Settings", None))
        self.SideMenu.setItemText(self.SideMenu.indexOf(self.SideMenuPage3), _translate("MainWindow", "Data plot", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuCalibrations.setTitle(_translate("MainWindow", "Calibrations", None))
        self.menuPreferences.setTitle(_translate("MainWindow", "Preferences", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionOpenSettings.setText(_translate("MainWindow", "Open...", None))
        self.actionSaveSettings.setText(_translate("MainWindow", "Save...", None))
        self.actionOpenCalibrations.setText(_translate("MainWindow", "Open...", None))
        self.actionSaveCalibrations.setText(_translate("MainWindow", "Save....", None))
        self.actionBootUpDelay.setText(_translate("MainWindow", "Boot Up Delay...", None))
        self.actionCommTimeout.setText(_translate("MainWindow", "Comm Timeout...", None))

import AQresources_rc
